### PR TITLE
Proposed script and github actions for checking ISO 3166-1

### PR DESCRIPTION
**Pull request by detrin**
I finished today a CLI tool that can fetch ISO 3166-1 list from iso.org. https://github.com/detrin/download-iso3166-list

I suggest adding this script and github action for regular checks of the list.

I didn't test the github action script, it is only proposed schema.

### CODE REVIEW

**Comment by deactivated** [comment]
Hi @detrin,

Thanks for the interest. This workflow isn't usable as is due to the dependency on a json file in an external repo.

**Comment by detrin** [comment]
You could use the CLI I prepared, or scrape the iso.org directly in github action with custom code @deactivated

**Comment by mjpieters** [comment]
> You could use the CLI I prepared

Note that your CLI requires that Chrome is installed.

**Comment by detrin** [comment]
My issue is that the reliance on human updates is not a reliable way to make updates.

**Pull request closed without merging**
